[project]
name = "http-server"
version = "0.0.0"
description = "Simple HTTP server implemented in Python."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"
extend_skip_glob = ".venv*"
